### ISSUE TITLE
Push a first release of the new aspen

### ISSUE THREAD

**Issue by Changaco** [AspenWeb/aspen.py#2]
Porting pando to aspen (https://github.com/AspenWeb/pando.py/issues/548) is complicated by the fact that the new aspen hasn't been released yet.

**Comment by Changaco** [comment]
I'm waiting for #20 to land before going ahead with this.

I'll need [PyPI access](https://pypi.python.org/pypi?:action=role_form&package_name=aspen) when the time comes.

About the version number, I think that using 0.43 as you suggested in https://github.com/AspenWeb/pando.py/issues/357#issuecomment-234092699 would only increase confusion. This isn't "just another release", it's such a massive change that we almost changed the name of the project to aspen-core.

**Comment by chadwhitacre** [comment]
> I'm waiting for #20 to land before going ahead with this.

👍

> I'll need PyPI access when the time comes.

Done (username Changaco, right?).

> About the version number,

I guess I didn't understand whether 1.0 [here](https://github.com/AspenWeb/aspen.io/issues/1#issuecomment-234088604) referred to Aspen or Pando. How about going ahead with 1.0.0 for this next release of Aspen, with 1.0.0 for Pando to follow in September?

**Comment by Changaco** [comment]
> Done (username Changaco, right?).

Yep. I can confirm that I now have access.

> I guess I didn't understand whether 1.0 [here](https://github.com/AspenWeb/aspen.io/issues/1#issuecomment-234088604) referred to Aspen or Pando. How about going ahead with 1.0.0 for this next release of Aspen, with 1.0.0 for Pando to follow in September?

I was talking about Aspen, not Pando. Here's my current thinking:

Soon: Aspen 1.0rc1 (instead of 0.90), Pando 0.43 or 0.50
September: Aspen 1.0, Pando 0.xx or 1.0 if we manage to close https://github.com/AspenWeb/pando.py/issues/357

**Comment by chadwhitacre** [comment]
Sounds good. I like 1.0rc1 for Aspen. I'd pick 0.43 over 0.50 for Pando.

**Comment by Changaco** [comment]
1.0rc1 released. The README isn't being rendered correctly [on PyPI](https://pypi.python.org/pypi/aspen), and the built wheel is python 3 only (we probably need a `setup.cfg`).

**Comment by Changaco** [comment]
Done \o/
