### ISSUE TITLE
List all implicit variables in Simplates context on one page

### ISSUE THREAD

**Issue by techtonik** [AspenWeb/aspen.py#403]
Some kind of reference page that list all variables that set automatically in Simplates context will be useful. For example, `path` is a very common name in my scripts, and while it makes sense, I was a little surprised.

There seems to be these variables:
- `path`
- `request`
- `response`

What else?

**Comment by pjz** [comment]
We now pass in all of the dependency-injected things set/returned in [algorithm/website.py](https://github.com/gratipay/aspen-python/blob/master/aspen/algorithms/website.py)

**Comment by whit537** [comment]
#30 would affect this. We'd want to list the available things to import.

**Comment by whit537** [comment]
Copied to #339.
