### ISSUE TITLE
Repoint aspen.io to RtD

### ISSUE THREAD

**Issue by chadwhitacre** [AspenWeb/aspen.py#42]
We still link to https://hackerone.com/gratipay from the footer of http://aspen.io/. Rather than update in `docs/`, I thought it might just be easier to switch http://aspen.io/ to point to http://aspen.readthedocs.io/en/latest/ instead of Heroku. Any objections, @Changaco?

**Comment by Changaco** [comment]
No objection.

**Comment by chadwhitacre** [comment]
[Done](http://aspen.io/)! 💃

**Comment by Changaco** [comment]
Note that RtD is currently configured to render the `docs` branch (#37), not `master`.

**Comment by chadwhitacre** [comment]
Good catch ...

**Comment by Changaco** [comment]
I've switched the RtD setting to `master`.
