### ISSUE TITLE
Broken test

### ISSUE THREAD

**Issue by Changaco** [AspenWeb/aspen.py#43]
https://travis-ci.org/AspenWeb/aspen.py/builds/210710915

**Comment by chadwhitacre** [comment]
Blorg. :thinking:

**Comment by Changaco** [comment]
I'm looking into this. I can reproduce the problem locally. I've tried several older commits including the ones tagged `1.0rc1` and `1.0rc2`, they all fail with the same error.

**Comment by Changaco** [comment]
The test is failing because new versions of `python-mimeparse` have been released which handle corner cases differently.
