### ISSUE TITLE
Gather Aspen conventions to one page 

### ISSUE THREAD

**Issue by techtonik** [AspenWeb/aspen.py#437]
While http://aspen.io/project_root/ is good for describing the existing stuff, it is not too easy to discover.

I'd enjoy reading a dedicated page about "Aspen Conventions" that has also historical insight sorted by version, so that it can also be used to port apps from previous versions.

**Comment by pjz** [comment]
I'm not quite sure what you're looking for wrt 'Aspen Conventions'; PRs accepted - even a rough page is better than nothing, and I'd be happy to fill in details, given a skeletal page to hang them on.

I moved the other half of your issue into its own separate issue at #438.

**Comment by techtonik** [comment]
Ruby on Rails has conventions where to put models, views etc. Django too. Aspen too. For a fully configurable project convention is the defaults. http://aspen.io/project_root/ basically about that, but it has different name.

**Comment by pjz** [comment]
So is there work to do here, or is this just a whinge that it's not what you're used to?

**Comment by whit537** [comment]
Ping @techtonik?

**Comment by whit537** [comment]
Hearing nothing ...
