### ISSUE TITLE
Website should receive instead of subclassing Configuration

### ISSUE THREAD

**Issue by whit537** [AspenWeb/aspen.py#444]
Reticketed from #441.

**Comment by pjz** [comment]
Agreed. IMO it should receive a plain dict instead of a complicated Configuration object.

**Comment by techtonik** [comment]
:+1: I don't have opinion about if it should be a dict or struct, but it should not be mixed into WSGI app class.

**Comment by whit537** [comment]
Talked on https://github.com/gratipay/aspen-python/issues/472 about this. Sounds like the driving concern is avoiding conflict between system and user configuration keys.

**Comment by whit537** [comment]
This is obsolete with #527.
