### ISSUE TITLE
What about a rc3 release to PyPI to finalize support for Python 3?

### ISSUE THREAD

**Issue by cclauss** [AspenWeb/aspen.py#48]
Last release was 9 months ago... https://github.com/AspenWeb/aspen.py/releases

**Comment by chadwhitacre** [comment]
Fine with me but I'm not going to be able to work on it myself. I'm hoping to be able to spend a few weeks on Aspen/Pando again in September or so.

**Comment by Changaco** [comment]
Time flies, eh? I'll do the release, but the only actual change in the library compared to rc2 will be #30 I think.

**Comment by Changaco** [comment]
Done.

Note: I tweaked `release.sh` in 1978dc9fadcee75993ad7eb8914731c16721f052.
