### ISSUE TITLE
spin Aspen out into a new org

### ISSUE THREAD

**Issue by whit537** [AspenWeb/aspen.py#547]
Aspen is currently housed under Gratipay. At https://github.com/gratipay/aspen.py/issues/526#issuecomment-174446901, @Changaco suggests spinning it out into its own entity:

> I had a thought last night: if aspen becomes a framework that can integrate into others, then it should be easy to integrate it with a nano-framework based on `algorithm.py`, which for lack of a better name (https://github.com/gratipay/algorithm.py/issues/3) could be called `aspen-standalone`, and eventually `aspen-legacy` if we all migrate away from it.
>
I think we should use aspen as an umbrella name, split it into separate libraries (`aspen-{fs-routing,simplates}` for the core and `aspen-{django,flask,standalone}` for the shells), and move all of those into separate repositories under a new aspen organization. The work in #527 wouldn't be lost, it would be the base for everything except the `standalone` shell.

**Comment by whit537** [comment]
@pjz What's your take?

**Comment by pjz** [comment]
Sure, I'm okay with that, though it likely introduces a bit of 'brand confusion'.  I think we'd better plan out the submodule layout a bit up front, though.

**Comment by whit537** [comment]
!m @pjz

**Comment by whit537** [comment]
@Changaco Is now a good time to jump ship to GitLab, or would you like to stay on GitHub?

**Comment by whit537** [comment]
> I think we'd better plan out the submodule layout a bit up front, though.

Here's a proposed target for repositories in the new org:

 - `aspen`—standalone web framework
 - `Flask-Aspen`—Flask integration
 - `django-aspen`—Django integration
 - `aspen-core`—dispatch + simplates
 - `algorithm.py`
 - `dependency_injection.py`
 - `filesystem_tree.py`

**Comment by clone1018** [comment]
Maybe fix the names while you have a chance?

`aspen`
`aspen-flask`
`aspen-django`
`aspen-core`
?

**Comment by Changaco** [comment]
@whit537 It looks like GitLab is still missing the Watch repo feature, are we okay with that?

**Comment by whit537** [comment]
@clone1018 That aligns with @Changaco's original suggestion. I proposed `Flask-Aspen` and `django-aspen` to align with norms for Flask and Django respectively:

> `Flask-Aspen` would be the normal name for a [Flask extension](http://flask.pocoo.org/extensions/), and `django-aspen` for a [Django package](https://www.djangopackages.com/).

https://github.com/gratipay/aspen.py/issues/526#issuecomment-176775232

**Comment by pjz** [comment]
Is a standalone webserver really what `aspen` is?

**Comment by whit537** [comment]
> It looks like GitLab is still missing the Watch repo feature, are we okay with that?

I'm fine with that. Seems likely they'll add it in the next year or two (or one of us can since they're open!), and it seems better to make the jump now rather than a year from now to avoid additional disruption down the line—we don't want to make @pjz update his remotes more than he has to. ;-)

**Comment by pjz** [comment]
wait, so all of aspen is moving to gitlab?  uhh... gitlab is also missing one other major feature: *speed*

**Comment by whit537** [comment]
> Is a standalone webserver really what `aspen` is?

Not since https://github.com/gratipay/aspen.py/issues/283. ;-)

Since then, we've been a standalone web*framework*. You and I were ready to shrink scope further in #526, but, as I see it, @Changaco is bringing us back from the brink on that one.

**Comment by whit537** [comment]
> wait, so all of aspen is moving to gitlab? uhh... gitlab is also missing one other major feature: *speed*

@pjz If you don't mind switching remotes again in a year or two then I'd be fine staying on GitHub for now. :)

**Comment by pjz** [comment]
You guys do whatever.  I've not been contributing much lately anyway.

**Comment by Changaco** [comment]
@whit537 I think we should try to untangle dispatch and simplates. Aside from that I'm +1 on your proposal.

**Comment by whit537** [comment]
> I think we should try to untangle dispatch and simplates.

Works for me.

> Aside from that I'm +1 on your proposal.

Cool.

**Comment by whit537** [comment]
Seems like we're ready for a new org here on GitHub! :-)

@Changaco Are you willing to set that up?

**Comment by Changaco** [comment]
Yeah, why not?

**Comment by Changaco** [comment]
https://github.com/aspen/ is already taken.

**Comment by whit537** [comment]
!m @Changaco

**Comment by Changaco** [comment]
Here are some available names: Aspen[-]Org, Aspen[-]Web, {python,py}-aspen, aspen-{py,python}.

**Comment by whit537** [comment]
@Changaco We're presently using the `aspen.io` domain—is AspenIO or aspen-io too goofy?

**Comment by whit537** [comment]
`aspen_`?

> single_trailing_underscore_ : used by convention to avoid conflicts with Python keyword

https://www.python.org/dev/peps/pep-0008/

**Comment by Changaco** [comment]
BTW, why is this project called Aspen? I'm not suggesting we change it, I'm just wondering, it seems to be a quite common name: https://github.com/search?utf8=%E2%9C%93&q=aspen

**Comment by whit537** [comment]
@Changaco I honestly don't remember. I've wondered the same thing. :-)

**Comment by Changaco** [comment]
Underscores aren't allowed in org names, only single hyphens, and not at the extremities.

**Comment by whit537** [comment]
> Underscores aren't allowed in org names, only single hyphens, and not at the extremities.

I'd be fine with a rename. Then maybe we could stick with `aspen` instead of `aspen-core`, for @pjz. ;-)

**Comment by whit537** [comment]
> Then maybe we could stick with `aspen` instead of `aspen-core`

Meaning, use the name `aspen` for the part that collects dispatch and simplates.

 - `_________`—standalone web framework
 - `Flask-Aspen`—Flask integration
 - `django-aspen`—Django integration
 - `aspen`—dispatch + simplates
 - `algorithm.py`
 - `dependency_injection.py`
 - `filesystem_tree.py`

**Comment by whit537** [comment]
https://en.wikipedia.org/wiki/Pando_(tree)

?

**Comment by whit537** [comment]
Squatters: https://github.com/pando. :-/

Could ping GitHub?

**Comment by Changaco** [comment]
> I'd be fine with a rename.

Okay, finding a good name tends to take time though.

> Then maybe we could stick with `aspen` instead of `aspen-core`, for @pjz.

Looks like an orthogonal issue to me, my original proposal was for aspen to be the umbrella name.

**Comment by Changaco** [comment]
> Squatters: https://github.com/pando. :-/

Could be a private org, right?

**Comment by whit537** [comment]
> Could be a private org, right?

That's a more charitable interpretation, yes. :-)

> Okay, finding a good name tends to take time though.

Indeed. :-)

`AspenFramework`?

**Comment by whit537** [comment]
`AspenWebFramework`?

**Comment by whit537** [comment]
@Changaco What's your leaning?

**Comment by Changaco** [comment]
I'm leaning towards AspenWeb.

**Comment by whit537** [comment]
:+1:

**Comment by Changaco** [comment]
@clone1018 @pjz Any objections to AspenWeb?

**Comment by Changaco** [comment]
https://github.com/AspenWeb created. @whit537 and @pjz invited.

**Comment by Changaco** [comment]
@whit537 https://github.com/gratipay/simplates.org wasn't part of the Aspen team of the Gratipay org, so I don't have access to transfer it to the new org.

**Comment by Changaco** [comment]
There's also `simplates.emacs` and the non-python `aspen.*` repos left.

**Comment by whit537** [comment]
!m @Changaco 

I've added the repos you mentioned to the Aspen team under Gratipay, so you should be able to migrate them now.

**Comment by whit537** [comment]
@Changaco Should we have a `salon` or other meta repo under AspenWeb to carry on with this discussion?

**Comment by Changaco** [comment]
> so you should be able to migrate them now

No can do, I only have read access.

> Should we have a salon or other meta repo under AspenWeb to carry on with this discussion?

Good idea.

**Comment by whit537** [comment]
> No can do, I only have read access.

Sorry ... try now?

**Comment by Changaco** [comment]
All done, I guess you can delete Gratipay's aspen-python team now.

I've also created the salon: https://github.com/AspenWeb/salon

**Comment by whit537** [comment]
> I guess you can delete Gratipay's aspen-python team now.

Done. And with that, I guess it's time to remove you from the Gratipay org as well. :cry: 

![screen shot 2016-02-17 at 10 44 36 am](https://cloud.githubusercontent.com/assets/134455/13114906/92fbe520-d563-11e5-9095-55b6107af449.png)

!m @Changaco

**Comment by Changaco** [comment]
Well, it's the second time I'm removed from there, actually. ;-)

**Comment by whit537** [comment]
:-P

Announced!

https://twitter.com/aspen_io/status/699986677519912960

**Comment by Changaco** [comment]
Time to close this issue I guess. The discussion is continuing in https://github.com/AspenWeb/salon/issues/1.

**Comment by whit537** [comment]
> uhh... gitlab is also missing one other major feature: *speed*

Looks like they just missed us:

> [GitLab.com](https://gitlab.com/gitlab-org/gitlab-ce) is now *a lot* faster across most of the site, check it out :)
>
We've [got a lot of merged PRs regarding performance recently](https://gitlab.com/gitlab-com/operations/issues/42), and we recently fixed a bug that has improved performance 3x for many pages! We'd love to have you :D

https://github.com/dear-github/dear-github/issues/56#issuecomment-185394431
