### ISSUE TITLE
Drop state chain?

### ISSUE THREAD

**Issue by Changaco** [AspenWeb/aspen.py#62]
The [`aspen.request_processor.algorithm` module](https://github.com/AspenWeb/aspen.py/blob/380ecf37069af939315115c42dc8c314e0920ac3/aspen/request_processor/algorithm.py) only contains 7 functions, and they're all very simple. I'm not sure using a state chain in Aspen still makes sense, framework wrappers may be better off gluing the pieces together themselves.

**Comment by chadwhitacre** [comment]
Would Pando still use `state_chain`?

**Comment by Changaco** [comment]
Yes. I like Pando's state chain, I'm just not sure Aspen still needs one.

**Comment by chadwhitacre** [comment]
sgtm
