### ISSUE TITLE
3.9 dropped support for Aspen "magic directories"

### ISSUE THREAD

**Issue by tsvi** [AspenWeb/aspen.py#92]
I was wondering if this relates to you guys. Looks like the link in the venv creation code is dead. From some googling and some common sense I deduced this might be the project that has been referred to.

Please see
https://bugs.python.org/issue37663
https://github.com/python/cpython/pull/14941

If I'm correct, I suggest you propose a fix to revert the issue.

**Comment by Changaco** [comment]
“magic directories” were dropped so long ago, I didn't even know about them.

After some research, I've found [an old PDF in the Internet Archive](https://web.archive.org/web/20101226044156/http://www.zetadev.com/software/aspen/0.8/doc/aspen-0.8.pdf) that talks about magic directories, and a remaining reference to them in the [obsolete doc website](https://github.com/AspenWeb/pando.py/tree/0.47/doc):

> Aspen can be configured with a project_root directory, a catchall for files that don't belong in your actual URL hierarchy.  Think of it as your site's junk drawer.
>
> Previous versions of Aspen hard-wired this to a directory named `.aspen` inside ${website.www_root}, but that was inflexible and people struggled with hidden directories on Mac OS. Even earlier versions used a cleverly-named __ directory as a virtualenv with a UNIX-y userland layout. So conf files were under `etc/`, modules under `lib/python/`, and templates under `etc/templates/`. For reasons of versioning and deployment (most of which were first put into my head by [Jim Fulton](http://mail.python.org/pipermail/web-sig/2007-March/002526.html)), it turns out to be better for `project_root` to be flat.
